# https://www.ranker.com/review/parmigiano-reggiano/1757757?ref=node_name&pos=2&a=0&ltype=n&l=361861&g=2

[translation]
  [translation.en]
    term = "parmigiano reggiano"
  [translation.es]
    term = "queso parmesano reggiano"
